# Generated by Django 5.2.7 on 2025-11-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocustomizado',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='usuariocustomizado',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='profile_pics/default_profile.png', null=True, upload_to='profile_pics/'),
        ),
    ]
