# Generated by Django 5.2.6 on 2025-09-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_livro_categoria_livro_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_devolucao_efetiva',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('devolvido', 'Devolvido'), ('atrasado', 'Atrasado')], default='ativa', max_length=20),
        ),
    ]
