# Generated by Django 5.2.6 on 2025-09-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reserva_data_devolucao_efetiva_reserva_observacoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='disponivel',
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_emprestimo',
            field=models.DateField(auto_now_add=True),
        ),
    ]
