# Generated by Django 5.2.7 on 2025-11-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_livro_disponivel_livro_quantidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='data_emprestimo',
            new_name='data_reserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_disponivel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('preparando', 'Em Preparação'), ('aguardando', 'Aguardando Retirada'), ('ativa', 'Emprestado (Retirado)'), ('devolvido', 'Devolvido'), ('atrasado', 'Atrasado')], default='preparando', max_length=20),
        ),
    ]
