# Generated by Django 5.2.7 on 2025-11-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_data_emprestimo_reserva_data_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_emprestimo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
