# Generated by Django 5.2.7 on 2025-11-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reserva_data_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='localizacao',
            field=models.CharField(blank=True, help_text='Ex: Corredor 3, Prateleira A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('preparando', 'Em Preparação'), ('aguardando', 'Aguardando Retirada'), ('ativa', 'Retirado'), ('devolvido', 'Devolvido'), ('atrasado', 'Atrasado')], default='preparando', max_length=20),
        ),
    ]
