# Generated by Django 5.2.7 on 2025-11-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_livro_localizacao_alter_reserva_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='livro',
            name='corredor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='prateleira',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
